In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.eye(5) #Diagonally 1 and others 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.52364502, 0.02886278, 0.12826801, 0.04333311, 0.78980847])

In [22]:
np.random.rand(5,5)

array([[0.2560057 , 0.89802111, 0.09523158, 0.75905327, 0.8868773 ],
       [0.14063793, 0.08434581, 0.25044008, 0.71780726, 0.85566876],
       [0.39674675, 0.39263078, 0.06448788, 0.65947771, 0.29075204],
       [0.49225174, 0.48413792, 0.17843908, 0.65966316, 0.71814278],
       [0.001365  , 0.64196502, 0.78662257, 0.68504855, 0.53437946]])

In [23]:
np.random.randn(2)  #two random numbers from standard distribution

array([ 0.17342081, -0.71702638])

In [24]:
np.random.randn(2,2)

array([[1.53754241, 0.43817712],
       [0.30832767, 1.69071623]])

In [25]:
np.random.randint(1,100)

39

In [27]:
np.random.randint(1,100,10) #low,high,size

array([ 2, 97, 42, 91, 24, 79, 29,  4, 77, 81], dtype=int32)

In [30]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 0, 38, 36, 18, 17, 14, 23,  9, 14, 49], dtype=int32)

In [31]:
arr.reshape(5,5) #5 row 5 colmn arr.reshape(5,10) won't wotk because original size required to be unchanged

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

np.int32(49)

In [33]:
ranarr.min()

np.int32(0)

In [34]:
ranarr.argmax()

np.int64(9)

In [35]:
ranarr.argmin()

np.int64(0)

In [36]:
arr.shape #(25,) indicates arr is an one dimensional

(25,)

In [37]:
arr = arr.reshape(5,5)

In [38]:
arr.shape

(5, 5)

In [39]:
arr.dtype

dtype('int64')

In [40]:
from numpy.random import randint #np.random.randint

In [42]:
randint(2,10)

6